trigger:
  branches:
    include:
      - main

variables:
  - group: terraform-variables  # This must include ARM_CLIENT_ID, ARM_CLIENT_SECRET, etc.

stages:
  - stage: LintValidate
    displayName: "Terraform Lint & Validate"
    jobs:
      - job: Validate
        pool:
          name: 'Default'
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                echo "##[group]Terraform Format"
                terraform fmt -check -recursive
                echo "##[endgroup]"

                echo "##[group]Terraform Init & Validate"
                terraform init -backend=false
                terraform validate
                echo "##[endgroup]"

  - stage: Plan
    displayName: "Terraform Plan"
    dependsOn: LintValidate
    jobs:
      - job: Plan
        pool:
          name: 'Default'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'terraform-cicd-arm'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                terraform init -reconfigure `
                  -backend-config="resource_group_name=$(BACKEND_RG)" `
                  -backend-config="storage_account_name=$(STORAGE_ACCOUNT_NAME)" `
                  -backend-config="container_name=tfstate" `
                  -backend-config="key=$(BACKEND_KEY)"

                terraform plan -out=tfplan
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System
